### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by jakub-olczyk** [paulchakravarti/pymodem#1]
Hello @paulchakravarti !

I couldn't find any LICENSE file and only licensing info I could find was in `setup.py` with info that it is "BSD" but this is very ambiguous statement.

Could you please provide some more information about this code's license?

Cheers!

**Comment by paulc** [comment]
The code is BSD licensed as noted in setup.py - I'm not sure what other information I can provide.

**Comment by jakub-olczyk** [comment]
My point is that there are [at least 3 types of BSD licenses](https://en.wikipedia.org/wiki/BSD_license#Terms) and they are quite different in details that are rather important. If you could specify which one do you prefer for this code it would be awesome and easier for other parties to contribute ;)

Differences between BSD licenses:
- 2-clause (FreeBSD license)
  - most permissive
  - similar to [MIT](https://en.wikipedia.org/wiki/MIT_License) or [ISC](https://en.wikipedia.org/wiki/ISC_license) license
  - allows for redistribution of copies (modified or not) under condition that the license text is somehow presentable for the user of the product containing your code
- 3-clause (New-BSD license)
  - requires that mention of your name in advertising is done with your written permission
- 4-clause  (Old BSD license)
  - most restrictive
  - requires that all advertising materials notify that derived product ships with your library 

All of the licenses have clauses of the previous one (so there probably is some nice Venn diagram describing the relation between them ;) )

I hope this clarifies my confusion ;)

Cheers!

**Comment by paulc** [comment]
I've updated to specify MIT license

Thanks, Paul
